[build]
  command = "echo 'No build needed'"
  functions = "netlify/functions"
  publish = "."

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/success"
  to = "/src/pages/success.html"
  status = 200

[[redirects]]
  from = "/mentions-legales"
  to = "/src/pages/mentions-legales.html"
  status = 200

[[redirects]]
  from = "/confidentialite"
  to = "/src/pages/confidentialite.html"
  status = 200

# API redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"], Country = ["US"]}

[functions]
  node_bundler = "esbuild"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true